// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Mars_Project_Automation.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Test scenarios for Languages and Skills")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class TestScenariosForLanguagesAndSkillsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Test scenarios for Languages and Skills", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "LanguageSkills.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A. Add a Language in Profile with valid name and level")]
        [NUnit.Framework.CategoryAttribute("Languages")]
        public async global::System.Threading.Tasks.Task A_AddALanguageInProfileWithValidNameAndLevel()
        {
            string[] tagsOfScenario = new string[] {
                    "Languages"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A. Add a Language in Profile with valid name and level", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
  await testRunner.AndAsync("I add the Language \'English\' with level \'Conversational\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
  await testRunner.ThenAsync("The Language \'English\' should appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("B. Add a duplicate Language (valid input, negative logic)")]
        public async global::System.Threading.Tasks.Task B_AddADuplicateLanguageValidInputNegativeLogic()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("B. Add a duplicate Language (valid input, negative logic)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
  await testRunner.AndAsync("I try to add the Language \'English\' again with level \'Conversational\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
  await testRunner.ThenAsync("The Language \'English\' should not be duplicated in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C. Add a Language in Profile with valid name and level")]
        public async global::System.Threading.Tasks.Task C_AddALanguageInProfileWithValidNameAndLevel()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("C. Add a Language in Profile with valid name and level", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
  await testRunner.AndAsync("I add the Language \'Hindi\' with level \'Fluent\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
  await testRunner.ThenAsync("The Language \'Hindi\' should appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("D. Edit a Language in Profile")]
        public async global::System.Threading.Tasks.Task D_EditALanguageInProfile()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("D. Edit a Language in Profile", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 24
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
  await testRunner.AndAsync("I edit the Language \'Hindi\' \'Urdu\' with level \'Conversational\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
  await testRunner.ThenAsync("The Language \'Urdu\' should appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("E. Add a Language in Profile with valid name and level")]
        public async global::System.Threading.Tasks.Task E_AddALanguageInProfileWithValidNameAndLevel()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("E. Add a Language in Profile with valid name and level", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
  await testRunner.AndAsync("I add the Language \'German\' with level \'Basic\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
  await testRunner.ThenAsync("The Language \'German\' should appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("F. Edit a Language to use symbols (destructive test)")]
        public async global::System.Threading.Tasks.Task F_EditALanguageToUseSymbolsDestructiveTest()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("F. Edit a Language to use symbols (destructive test)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
  await testRunner.AndAsync("I edit the Language \'German\' \'@@@@\' with level \'Fluent\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
  await testRunner.ThenAsync("The Language \'@@@@\' should appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("G. Add a Language in Profile with valid name and level")]
        public async global::System.Threading.Tasks.Task G_AddALanguageInProfileWithValidNameAndLevel()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("G. Add a Language in Profile with valid name and level", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
  await testRunner.AndAsync("I add the Language \'French\' with level \'Fluent\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
  await testRunner.ThenAsync("The Language \'French\' should appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("H. Add a Language in Profile with valid name and level")]
        public async global::System.Threading.Tasks.Task H_AddALanguageInProfileWithValidNameAndLevel()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("H. Add a Language in Profile with valid name and level", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
  await testRunner.AndAsync("I try to add the Language \'Spanish\' with level \'Basic\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
  await testRunner.ThenAsync("The Language \'Spanish\' should not be added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I. Delete a Language in Profile with valid name and level")]
        public async global::System.Threading.Tasks.Task I_DeleteALanguageInProfileWithValidNameAndLevel()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("I. Delete a Language in Profile with valid name and level", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
  await testRunner.AndAsync("I delete the Language \'Urdu\' with level \'Conversational\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
  await testRunner.ThenAsync("The Language \'Urdu\' should not appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("J. Delete a Language in Profile with valid name and level")]
        public async global::System.Threading.Tasks.Task J_DeleteALanguageInProfileWithValidNameAndLevel()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("J. Delete a Language in Profile with valid name and level", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
  await testRunner.AndAsync("I delete the Language \'@@@@\' with level \'Fluent\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
  await testRunner.ThenAsync("The Language \'@@@@\' should not appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("K. Delete a Language in Profile with valid name and level")]
        public async global::System.Threading.Tasks.Task K_DeleteALanguageInProfileWithValidNameAndLevel()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("K. Delete a Language in Profile with valid name and level", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 66
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
  await testRunner.AndAsync("I delete the Language \'French\' with level \'Fluent\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
  await testRunner.ThenAsync("The Language \'French\' should not appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("L. Add a Language with empty fields")]
        public async global::System.Threading.Tasks.Task L_AddALanguageWithEmptyFields()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("L. Add a Language with empty fields", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 71
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
  await testRunner.AndAsync("I try to add the Language \' \' with level \' \'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
  await testRunner.ThenAsync("The Language \' \' should not be added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("M. Add a Language with only numbers (invalid input)")]
        public async global::System.Threading.Tasks.Task M_AddALanguageWithOnlyNumbersInvalidInput()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("M. Add a Language with only numbers (invalid input)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 77
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
  await testRunner.AndAsync("I try to add the Language \'1234\' with level \'Basic\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
  await testRunner.ThenAsync("The Language \'1234\' should be added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("N. Add a Language with special characters (destructive input)")]
        public async global::System.Threading.Tasks.Task N_AddALanguageWithSpecialCharactersDestructiveInput()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("N. Add a Language with special characters (destructive input)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 84
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 85
  await testRunner.AndAsync("I try to add the Language \'!@#$%\' with level \'Fluent\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
  await testRunner.ThenAsync("The Language \'!@#$%\' should be added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("O. Add a Language with a very long string")]
        public async global::System.Threading.Tasks.Task O_AddALanguageWithAVeryLongString()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("O. Add a Language with a very long string", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 88
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 89
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 90
  await testRunner.WhenAsync("I navigate to the Profile\'s Language section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 91
  await testRunner.AndAsync("I try to add the Language \'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
                        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\' with level \'Conversational\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
  await testRunner.ThenAsync("The Language \'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
                        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\' should be added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A. Add a Skill with valid name and level")]
        [NUnit.Framework.CategoryAttribute("Skills")]
        public async global::System.Threading.Tasks.Task A_AddASkillWithValidNameAndLevel()
        {
            string[] tagsOfScenario = new string[] {
                    "Skills"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A. Add a Skill with valid name and level", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 96
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
  await testRunner.WhenAsync("I navigate to the Profile\'s Skills section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
  await testRunner.AndAsync("I add the Skill \'Testing\' with level \'Expert\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
  await testRunner.ThenAsync("The Skill \'Testing\' should appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("B. Add a duplicate Skill")]
        public async global::System.Threading.Tasks.Task B_AddADuplicateSkill()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("B. Add a duplicate Skill", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 102
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
  await testRunner.WhenAsync("I navigate to the Profile\'s Skills section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 104
  await testRunner.AndAsync("I try to add the Skill \'Testing\' again with level \'Expert\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
  await testRunner.ThenAsync("The Skill \'Testing\' should not be duplicated in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C. Add a Skill with empty fields")]
        public async global::System.Threading.Tasks.Task C_AddASkillWithEmptyFields()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("C. Add a Skill with empty fields", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 107
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 108
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
  await testRunner.WhenAsync("I navigate to the Profile\'s Skills section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
  await testRunner.AndAsync("I try to add the Skill \' \' with level \' \'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
  await testRunner.ThenAsync("The Skill \' \' should not be added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("D. Add a Skill with only numbers")]
        public async global::System.Threading.Tasks.Task D_AddASkillWithOnlyNumbers()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("D. Add a Skill with only numbers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 113
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 114
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 115
  await testRunner.WhenAsync("I navigate to the Profile\'s Skills section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
  await testRunner.AndAsync("I try to add the Skill \'0987\' with level \'Intermediate\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
  await testRunner.ThenAsync("The Skill \'0987\' should be added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("E. Add a Skill with special characters")]
        public async global::System.Threading.Tasks.Task E_AddASkillWithSpecialCharacters()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("E. Add a Skill with special characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 119
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 120
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 121
  await testRunner.WhenAsync("I navigate to the Profile\'s Skills section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 122
  await testRunner.AndAsync("I try to add the Skill \'&^#@)}:\' with level \'Beginner\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
  await testRunner.ThenAsync("The Skill \'&^#@)}:\' should be added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("F. Add a Skill with a very long string")]
        public async global::System.Threading.Tasks.Task F_AddASkillWithAVeryLongString()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("F. Add a Skill with a very long string", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 125
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 126
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 127
  await testRunner.WhenAsync("I navigate to the Profile\'s Skills section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 128
  await testRunner.AndAsync("I try to add the Skill \'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
                        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\' with level \'Expert\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
  await testRunner.ThenAsync("The Skill \'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
                        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\' should be added", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("G. Edit a Skill")]
        public async global::System.Threading.Tasks.Task G_EditASkill()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("G. Edit a Skill", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 131
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 132
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 133
  await testRunner.WhenAsync("I navigate to the Profile\'s Skills section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 134
  await testRunner.AndAsync("I edit the Skill \'Testing\' to \'Automation\' with level \'Expert\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
  await testRunner.ThenAsync("The Skill \'Automation\' should appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("H. Delete a Skill")]
        public async global::System.Threading.Tasks.Task H_DeleteASkill()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("H. Delete a Skill", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 137
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 138
  await testRunner.GivenAsync("I log into Localhost portal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 139
  await testRunner.WhenAsync("I navigate to the Profile\'s Skills section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 140
  await testRunner.AndAsync("I delete the Skill \'Automation\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
  await testRunner.ThenAsync("The Skill \'Automation\' should not appear in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
